Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blogs.urls', 'blogs'), namespace='blogs')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Page for adding a new post
    path('new_post/', views.new_post, name='new_post'),

    # Page for editing existing posts
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(), {'template_name': 'registration/login.html'}, name='login'),

    # Logout page
    path('logout/', views.logout_view, name='logout'),

    # Registration page
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):
    """A post the user can publish."""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_deferred_fields(self):
        return self.title, self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost


class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import BlogPost
from .forms import PostForm


def index(request):
    """The home page for Blog. It shows the sorted list of posts in the blog."""
    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts': posts}
    return render(request, 'blogs/index.html', context)


@login_required
def new_post(request):
    """Add a new post."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = PostForm()
    else:
        # POST data submitted; process data.
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save('new_post')
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Edit an existing post."""
    post = BlogPost.objects.get(id=post_id)
    check_post_owner(request, post)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current post.
        form = PostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form, 'post': post}
    return render(request, 'blogs/edit_post.html', context)


def check_post_owner(request, post):
    # Make sure the post belong to the current user.
    if post.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Blog</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>

    <body>

        <!--Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                            ...
                    </button>
                    <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticatd %}
                            <li><a>Hello, {{ user.username }}</a> </li>
                            <li><a href="{% url 'users:logout' %}">log out</a> </li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">register</a> </li>
                            <li><a href="{% url 'users:login' %}">log in</a> </li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->

            </div>
        </nav>

        <div class="container">

            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div><!-- /container -->

    </body>
</html>

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    Edit post:
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'blogs:edit_post' post.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}

    </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <div class="jumbotron">
        <h1 style="text-align: center">A shared blog</h1>
    </div>
{% endblock header %}

{% block content %}

    <h2><a href="{% url 'blogs:new_post' %}">Add a new post</a></h2><br>

    <h2>Posts:</h2>

    {% for post in posts %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ post.owner }}
                    ({{ post.date_added|date:'M d, Y H:i' }}):
                    {{ post.title }}
                    <small>
                        <a href="{% url 'blogs:edit_post' post.id %}">
                            edit post
                        </a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ post.text|linebreaks }}
            </div>
        </div><!-- panel -->
    {% empty %}
        No posts have been added yet.
    {% endfor %}
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new post:</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'blogs:new_post' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add post</button>
        {% endbuttons %}
    </form>

{% endblock content %}